# config.py

# GitHub
GITHUB_TOKENS = ["ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "ghp_BBBBBBBBBBBBBBBBBBBBBBBBBB"]

# Telegram
TELEGRAM_TOKEN = "0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
TELEGRAM_GROUP_ID = "-1000000000000"  # ID группы
TELEGRAM_TOPIC_ID = "8"  # ID топика в группе
